In [145]:
import sqlite3
import requests
import xmltodict

In [153]:

response = requests.get('https://knesset.gov.il/Odata/ParliamentInfo.svc/KNS_BillUnion()') #   Based on the question was asked in the group by Neta
dict_data = xmltodict.parse(response.content)
# print(type(dict_data))
# print(dict_data)
# dict_data

In [147]:
db = sqlite3.connect('my_database.db')
cursor = db.cursor()
cursor.execute(
        '''
        CREATE TABLE IF NOT EXISTS KNS_BillName(
        BillUnionID INTEGER PRIMARY KEY,
        MainBillID INTEGER, 
        UnionBillID INTEGER ,  
        LastUpdatedDate TEXT)
        ''' )
db.commit()
atributes =[]

In [148]:
for element in dict_data['feed']['entry']:
    atribute = element['content']['m:properties']
    BillUnionID = int(atribute['d:BillUnionID']['#text'])
    MainBillID= int(atribute['d:MainBillID']['#text'])
    UnionBillID = int(atribute['d:UnionBillID']['#text'])
    LastUpdatedDate = atribute['d:LastUpdatedDate']['#text']
    atributes.append(( MainBillID,UnionBillID, LastUpdatedDate))

In [149]:
# atributes = [BillNameID, Name,NameHistoryTypeID, NameHistoryTypeDesc, LastUpdatedDate]
print(len(atributes))
atributes[:100]

100

[(31252, 37664, '2015-03-20T12:03:33'),
 (37668, 18516, '2015-03-20T12:03:33'),
 (37666, 37665, '2015-03-20T12:03:33'),
 (37660, 37659, '2015-03-20T12:03:33'),
 (37658, 17670, '2015-03-20T12:03:33'),
 (37658, 19438, '2015-03-20T12:03:33'),
 (31717, 31716, '2015-03-20T12:03:33'),
 (17834, 19677, '2015-03-20T12:03:33'),
 (77290, 77291, '2015-03-20T12:03:33'),
 (77287, 25317, '2015-03-20T12:03:33'),
 (18437, 31724, '2015-03-20T12:03:33'),
 (74963, 74962, '2015-03-20T12:03:33'),
 (75301, 75300, '2015-03-20T12:03:33'),
 (75198, 75199, '2015-03-20T12:03:33'),
 (75194, 75193, '2015-03-20T12:03:33'),
 (86881, 75191, '2015-03-20T12:03:33'),
 (30393, 86436, '2015-03-20T12:03:33'),
 (30393, 86438, '2015-03-20T12:03:33'),
 (30393, 86437, '2015-03-20T12:03:33'),
 (76098, 20605, '2015-03-20T12:03:33'),
 (75078, 75037, '2015-03-20T12:03:33'),
 (75078, 75079, '2015-03-20T12:03:33'),
 (30643, 31042, '2015-03-20T12:03:33'),
 (24306, 77772, '2015-03-20T12:03:33'),
 (77667, 25663, '2015-03-20T12:03:33'),
 (78362, 75217, '2015-03-20T12:03:33'),
 (78362, 75244, '2015-03-20T12:03:33'),
 (17655, 75250, '2015-03-20T12:03:33'),
 (75219, 75221, '2015-03-20T12:03:33'),
 (75219, 75222, '2015-03-20T12:03:33'),
 (75219, 75223, '2015-03-20T12:03:33'),
 (75219, 75224, '2015-03-20T12:03:33'),
 (75219, 17789, '2015-03-20T12:03:33'),
 (75219, 18506, '2015-03-20T12:03:33'),
 (75245, 17771, '2015-03-20T12:03:33'),
 (75245, 75246, '2015-03-20T12:03:33'),
 (75245, 75247, '2015-03-20T12:03:33'),
 (21666, 75248, '2015-03-20T12:03:33'),
 (77518, 17834, '2015-03-20T12:03:33'),
 (18905, 75190, '2015-03-20T12:03:33'),
 (89821, 75192, '2015-03-20T12:03:33'),
 (75188, 75189, '2015-03-20T12:03:33'),
 (75341, 29605, '2015-03-20T12:03:33'),
 (30534, 81390, '2015-03-20T12:03:33'),
 (37656, 85430, '2015-03-20T12:03:33'),
 (85368, 17764, '2015-03-20T12:03:33'),
 (85368, 75907, '2015-03-20T12:03:33'),
 (85368, 75909, '2015-03-20T12:03:33'),
 (100249, 97075, '2015-03-20T12:03:33'),
 (100249, 81414, '2015-03-20T12:03:33'),
 (78945, 79545, '2015-03-20T12:03:33'),
 (26858, 75083, '2015-03-20T12:03:33'),
 (26858, 26156, '2015-03-20T12:03:33'),
 (26858, 83779, '2015-03-20T12:03:33'),
 (26858, 30497, '2015-03-20T12:03:33'),
 (26858, 25252, '2015-03-20T12:03:33'),
 (17516, 19801, '2015-03-20T12:03:33'),
 (77518, 75218, '2015-03-20T12:03:33'),
 (27015, 21541, '2015-03-20T12:03:33'),
 (87934, 106518, '2015-03-20T12:03:33'),
 (86725, 86802, '2015-03-20T12:03:33'),
 (86725, 86514, '2015-03-20T12:03:33'),
 (132065, 132187, '2015-03-20T12:03:33'),
 (132065, 132353, '2015-03-20T12:03:33'),
 (132065, 134725, '2015-03-20T12:03:33'),
 (132065, 134564, '2015-03-20T12:03:33'),
 (132065, 130343, '2015-03-20T12:03:33'),
 (75027, 132394, '2015-03-20T12:03:33'),
 (130397, 130536, '2015-03-20T12:03:33'),
 (130397, 130908, '2015-03-20T12:03:33'),
 (130397, 139065, '2015-03-20T12:03:33'),
 (130397, 142320, '2015-03-20T12:03:33'),
 (135664, 143152, '2015-03-20T12:03:33'),
 (140027, 133176, '2015-03-20T12:03:33'),
 (130325, 181784, '2015-03-20T12:03:33'),
 (242230, 183846, '2015-03-20T12:03:33'),
 (135137, 144166, '2015-03-20T12:03:33'),
 (139134, 130480, '2015-03-20T12:03:33'),
 (286171, 254156, '2015-03-20T12:03:33'),
 (241021, 241346, '2015-03-20T12:03:33'),
 (324291, 325536, '2015-03-20T12:03:33'),
 (321196, 324986, '2015-03-20T12:03:33'),
 (317905, 318581, '2015-03-20T12:03:33'),
 (333807, 327447, '2015-03-20T12:03:33'),
 (328001, 330565, '2015-03-20T12:03:33'),
 (336378, 368610, '2015-03-20T12:03:33'),
 (419938, 414876, '2015-03-20T12:03:33'),
 (388389, 318928, '2015-03-20T12:03:33'),
 (388389, 405862, '2015-03-20T12:03:33'),
 (388389, 408546, '2015-03-20T12:03:33'),
 (388389, 409820, '2015-03-20T12:03:33'),
 (415700, 399149, '2015-03-20T12:03:33'),
 (318784, 326265, '2015-03-20T12:03:33'),
 (429388, 428075, '2015-03-20T12:03:33'),
 (343932, 419208, '2015-03-20T12:03:33'),
 (432374, 429225, '2015-03-20T12:03:33'),
 (342277, 425220, '2015-03-20T12:03:33'),
 (478316, 479235, '2015-03-20T12:03:33'),
 (477296, 478404, '2015-03-20T12:03:33'),
 (477296, 483621, '2015-03-20T12:03:33')]

In [150]:
cursor.executemany('''
                INSERT INTO KNS_BillName(

MainBillID,
UnionBillID,
LastUpdatedDate
)
                 VALUES (?,?,?)''', atributes)
cursor.execute('''
                   SELECT * FROM KNS_BillName
                   ''')

In [151]:
print ( "תאריך     " ,"קוד-מ", "קוד",  "מס")
for row in cursor:
     print(row,"   ")

תאריך      קוד-מ קוד מס
(1, 31252, 37664, '2015-03-20T12:03:33')
(2, 37668, 18516, '2015-03-20T12:03:33')
(3, 37666, 37665, '2015-03-20T12:03:33')
(4, 37660, 37659, '2015-03-20T12:03:33')
(5, 37658, 17670, '2015-03-20T12:03:33')
(6, 37658, 19438, '2015-03-20T12:03:33')
(7, 31717, 31716, '2015-03-20T12:03:33')
(8, 17834, 19677, '2015-03-20T12:03:33')
(9, 77290, 77291, '2015-03-20T12:03:33')
(10, 77287, 25317, '2015-03-20T12:03:33')
(11, 18437, 31724, '2015-03-20T12:03:33')
(12, 74963, 74962, '2015-03-20T12:03:33')
(13, 75301, 75300, '2015-03-20T12:03:33')
(14, 75198, 75199, '2015-03-20T12:03:33')
(15, 75194, 75193, '2015-03-20T12:03:33')
(16, 86881, 75191, '2015-03-20T12:03:33')
(17, 30393, 86436, '2015-03-20T12:03:33')
(18, 30393, 86438, '2015-03-20T12:03:33')
(19, 30393, 86437, '2015-03-20T12:03:33')
(20, 76098, 20605, '2015-03-20T12:03:33')
(21, 75078, 75037, '2015-03-20T12:03:33')
(22, 75078, 75079, '2015-03-20T12:03:33')
(23, 30643, 31042, '2015-03-20T12:03:33')
(24, 24306, 77772, '2015-03-20T12:03:33')
(25, 77667, 25663, '2015-03-20T12:03:33')
(26, 78362, 75217, '2015-03-20T12:03:33')
(27, 78362, 75244, '2015-03-20T12:03:33')
(28, 17655, 75250, '2015-03-20T12:03:33')
(29, 75219, 75221, '2015-03-20T12:03:33')
(30, 75219, 75222, '2015-03-20T12:03:33')
(31, 75219, 75223, '2015-03-20T12:03:33')
(32, 75219, 75224, '2015-03-20T12:03:33')
(33, 75219, 17789, '2015-03-20T12:03:33')
(34, 75219, 18506, '2015-03-20T12:03:33')
(35, 75245, 17771, '2015-03-20T12:03:33')
(36, 75245, 75246, '2015-03-20T12:03:33')
(37, 75245, 75247, '2015-03-20T12:03:33')
(38, 21666, 75248, '2015-03-20T12:03:33')
(39, 77518, 17834, '2015-03-20T12:03:33')
(40, 18905, 75190, '2015-03-20T12:03:33')
(41, 89821, 75192, '2015-03-20T12:03:33')
(42, 75188, 75189, '2015-03-20T12:03:33')
(43, 75341, 29605, '2015-03-20T12:03:33')
(44, 30534, 81390, '2015-03-20T12:03:33')
(45, 37656, 85430, '2015-03-20T12:03:33')
(46, 85368, 17764, '2015-03-20T12:03:33')
(47, 85368, 75907, '2015-03-20T12:03:33')
(48, 85368, 75909, '2015-03-20T12:03:33')
(49, 100249, 97075, '2015-03-20T12:03:33')
(50, 100249, 81414, '2015-03-20T12:03:33')
(51, 78945, 79545, '2015-03-20T12:03:33')
(52, 26858, 75083, '2015-03-20T12:03:33')
(53, 26858, 26156, '2015-03-20T12:03:33')
(54, 26858, 83779, '2015-03-20T12:03:33')
(55, 26858, 30497, '2015-03-20T12:03:33')
(56, 26858, 25252, '2015-03-20T12:03:33')
(57, 17516, 19801, '2015-03-20T12:03:33')
(58, 77518, 75218, '2015-03-20T12:03:33')
(59, 27015, 21541, '2015-03-20T12:03:33')
(60, 87934, 106518, '2015-03-20T12:03:33')
(61, 86725, 86802, '2015-03-20T12:03:33')
(62, 86725, 86514, '2015-03-20T12:03:33')
(63, 132065, 132187, '2015-03-20T12:03:33')
(64, 132065, 132353, '2015-03-20T12:03:33')
(65, 132065, 134725, '2015-03-20T12:03:33')
(66, 132065, 134564, '2015-03-20T12:03:33')
(67, 132065, 130343, '2015-03-20T12:03:33')
(68, 75027, 132394, '2015-03-20T12:03:33')
(69, 130397, 130536, '2015-03-20T12:03:33')
(70, 130397, 130908, '2015-03-20T12:03:33')
(71, 130397, 139065, '2015-03-20T12:03:33')
(72, 130397, 142320, '2015-03-20T12:03:33')
(73, 135664, 143152, '2015-03-20T12:03:33')
(74, 140027, 133176, '2015-03-20T12:03:33')
(75, 130325, 181784, '2015-03-20T12:03:33')
(76, 242230, 183846, '2015-03-20T12:03:33')
(77, 135137, 144166, '2015-03-20T12:03:33')
(78, 139134, 130480, '2015-03-20T12:03:33')
(79, 286171, 254156, '2015-03-20T12:03:33')
(80, 241021, 241346, '2015-03-20T12:03:33')
(81, 324291, 325536, '2015-03-20T12:03:33')
(82, 321196, 324986, '2015-03-20T12:03:33')
(83, 317905, 318581, '2015-03-20T12:03:33')
(84, 333807, 327447, '2015-03-20T12:03:33')
(85, 328001, 330565, '2015-03-20T12:03:33')
(86, 336378, 368610, '2015-03-20T12:03:33')
(87, 419938, 414876, '2015-03-20T12:03:33')
(88, 388389, 318928, '2015-03-20T12:03:33')
(89, 388389, 405862, '2015-03-20T12:03:33')
(90, 388389, 408546, '2015-03-20T12:03:33')
(91, 388389, 409820, '2015-03-20T12:03:33')
(92, 415700, 399149, '2015-03-20T12:03:33')
(93, 318784, 326265, '2015-03-20T12:03:33')
(94, 429388, 428075, '2015-03-20T12:03:33')
(95, 343932, 419208, '2015-03-20T12:03:33')
(96, 432374, 429225, '2015-03-20T12:03:33')
(97, 342277, 425220, '2015-03-20T12:03:33')
(98, 478316, 479235, '2015-03-20T12:03:33')
(99, 477296, 478404, '2015-03-20T12:03:33')
(100, 477296, 483621, '2015-03-20T12:03:33')

In [152]:
db.close()